- name: Auth to kube with provision_data.users environment variables
  community.okd.openshift_auth:
    validate_certs: false
    username: "{{ provision_data.openshift_cluster_admin_username }}"
    password: "{{ provision_data.openshift_cluster_admin_password }}"
    host: "{{ provision_data.openshift_api_server_url }}"
  register: _auth_rez

- name: Debug  username
  ansible.builtin.debug:
    msg: "USERNAME: {{ _user_name }}"

- name: Get all Plans in the mtv namespace
  environment:
    K8S_AUTH_API_KEY: "{{ _auth_rez.openshift_auth.api_key }}"
    K8S_AUTH_HOST: "{{ provision_data.openshift_api_server_url }}"
    K8S_AUTH_VERIFY_SSL: "false"
  kubernetes.core.k8s_info:
    namespace: "mtv-{{ _user_name }}"
    kind: Plan
    api_version: forklift.konveyor.io/v1beta1
  register: _plans

- name: Archive all Plans in the mtv namespace
  when: not delete_plans | bool
  environment:
    K8S_AUTH_API_KEY: "{{ _auth_rez.openshift_auth.api_key }}"
    K8S_AUTH_HOST: "{{ provision_data.openshift_api_server_url }}"
    K8S_AUTH_VERIFY_SSL: "false"
  kubernetes.core.k8s:
    namespace: "mtv-{{ _user_name }}"
    kind: Plan
    api_version: forklift.konveyor.io/v1beta1
    state: patched
    name: "{{ item.metadata.name }}"
    definition:
      spec:
        archived: true
  loop: "{{ _plans.resources }}"

- name: Debug me
  ansible.builtin.debug:
    msg: Debugging 

- name: Stuff Goes here
  when: delete_plans | bool
  environment:
    K8S_AUTH_API_KEY: "{{ _auth_rez.openshift_auth.api_key }}"
    K8S_AUTH_HOST: "{{ provision_data.openshift_api_server_url }}"
    K8S_AUTH_VERIFY_SSL: "false"

  block:

    - name: Delete the plans
      kubernetes.core.k8s:
        namespace: "mtv-{{ _user_name }}"
        kind: Plan
        api_version: forklift.konveyor.io/v1beta1
        state: absent
        name: "{{ item.metadata.name }}"
      loop: "{{ _plans.resources }}"

    - name: Delete StorageMaps in the mtv namespace
      kubernetes.core.k8s:
        namespace: "mtv-{{ _user_name }}"
        kind: StorageMap
        api_version: forklift.konveyor.io/v1beta1
        state: absent
        delete_all: true

    - name: Delete NetworkMaps in the mtv namespace
      kubernetes.core.k8s:
        namespace: "mtv-{{ _user_name }}"
        kind: NetworkMap
        api_version: forklift.konveyor.io/v1beta1
        state: absent
        delete_all: true

    - name: Delete the migrations
      kubernetes.core.k8s:
        namespace: "mtv-{{ _user_name }}"
        kind: Migration
        api_version: forklift.konveyor.io/v1beta1
        state: absent
        delete_all: true

    - name: Delete VMs in the vmexamples namespace
      kubernetes.core.k8s:
        namespace: "vmexamples-{{ _user_name }}"
        kind: VirtualMachine
        api_version: kubevirt.io/v1
        state: absent
        delete_all: true

