---
- name: Remove VMs
  hosts: localhost
  tasks:

    - name: Delete the 'linuxvm' namespace
      kubernetes.core.k8s:
        name: linuxvm
        kind: Namespace
        api_version: v1
        state: absent
