- name: Auth to kube with provision_data.users environment variables
  community.okd.openshift_auth:
    validate_certs: false
    username: "{{ _user_name }}"
    password: "{{ _user_password }}"
    host: "{{ provision_data.openshift_api_server_url }}"
  register: _auth_rez

- name: Block to call virt_plan role

  environment:
    K8S_AUTH_API_KEY: "{{ _auth_rez.k8s_auth.api_key }}"
    K8S_AUTH_HOST: "{{ provision_data.openshift_api_server_url }}"
    K8S_AUTH_VERIFY_SSL: "false"
    VMWARE_VALIDATE_CERTS: "false"
    VMWARE_HOST: "{{ vcenter_hostname }}"
    VMWARE_PASSWORD: "{{ vcenter_password }}"
    VMWARE_USER: "{{ vcenter_username }}"

  block:
    - name: Call role for users with vmware credentials in envrionment
      ansible.builtin.include_role:
        name: rlopez.ocp_virt.virt_plan
      vars:
        migration_namespace: "mtv-{{ _user_name }}"
        migration_target_namespace: "vmexamples-{{ _user_name }}"
        networkmap_name: "networkmap-{{ _user_name }}"
        storagemap_name: "storagemap-{{ _user_name }}"
        plan_name: "plan-{{ _user_name }}"
        user_selected_vm_names: "database\nwinweb01\nwinweb02"
